### ISSUE TITLE
Help me to run this project on my local

### ISSUE THREAD

**Issue by infinite41207** [ShahzaibAyyub/react-web3modal-v2#1]
Hello Shahzaib, how are you?
I'm Nemanja from Serbia. I have to integrate web3modal 2 to my project so, I've searched react project with web3modal 2 and noticed your repository is really great!
So, I think to run on my local btw, I'm getting error while install node_modules.
I'll really appreciate if you give me some tips to escape out of this errors.

My contacts are Email: infinite41207@gmail.com, Skype: live:.cid.117f09fcdd9718be

Best Regards

**Comment by ShahzaibAyyub** [comment]
Just do 'npm install' to download all the relevant packages

**Comment by infinite41207** [comment]
Thanks for your response
I did 'npm install' but got this error

![image](https://github.com/ShahzaibAyyub/react-web3modal-v2/assets/123818207/8e2a7cf0-9c5a-4a3d-a3b3-5f1d1f7738fc)

Could you help me to know what is this issue?

Thanks

**Comment by infinite41207** [comment]
![image](https://github.com/ShahzaibAyyub/react-web3modal-v2/assets/123818207/02878711-71a1-415c-b58c-34e28515958b)
Sure, I did 'npm install' but got this error
Could you tell me what should I have to do?
Thanks
